services:
  asm32:
    platform: linux/386          # here, not inside build
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - ..:/src
    stdin_open: true
    tty: true
